version: "3.3"

services: 
  backend:
    build: ../build/go/
    ports: 
      - "3000:3000"
    volumes: 
      - "../:/go/src/school"
      - "../build/pkg/:/go/pkg/"
    links: 
      - store
    tty: true
  
  store:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes: 
      - "../build/db:/var/lib/postgresql/data/"

  nginx:
    build: ../web/docker/nginx
    tty: true
    ports: 
      - "80:80"
    volumes: 
      - "../web/school-front/dist:/app"
      - "../web/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"

  frontend:
    image: node
    tty: true
    volumes:
      - "../web/school-front:/app"
  