version: "3.3"

services: 
  backend:
    build: ../build/docker/go/
    ports: 
      - "3000:3000"
    volumes: 
      - "../:/go/src/school"
      - "../build/docker/pkg/:/go/pkg/"
    links: 
      - store
    tty: true
  
  store:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes: 
      - "../build/docker/db:/var/lib/postgresql/data/"

  redis:
    image: redis
    volumes: 
      - "../build/docker/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf"
      - "../build/docker/redis/data:/data"
    ports: 
      - "6379:6379"

  nginx:
    build: ../web/docker/nginx
    tty: true
    ports: 
      - "80:80"
    volumes: 
      - "../web/school-front/dist:/app"
      - "../web/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - frontend

  frontend:
    image: node
    tty: true
    ports: 
      - "8080:8080"
    volumes:
      - "../web/school-front:/app"

  
  